"""empty message

Revision ID: 2f373f71e2ab
Revises: 3560bda602ac
Create Date: 2014-03-26 13:46:04.385475

"""

# revision identifiers, used by Alembic.
revision = '2f373f71e2ab'
down_revision = '3560bda602ac'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_name', table_name='user')
    op.create_index('ix_user_name', 'user', ['name'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_name', table_name='user')
    op.create_index('ix_user_name', 'user', ['name'], unique=1)
    ### end Alembic commands ###
