"""empty message

Revision ID: 3560bda602ac
Revises: acbe1fecdc3
Create Date: 2014-03-26 13:25:49.002114

"""

# revision identifiers, used by Alembic.
revision = '3560bda602ac'
down_revision = 'acbe1fecdc3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('pw_hash', sa.String(length=60), nullable=True))
    op.create_index('ix_user_pw_hash', 'user', ['pw_hash'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_pw_hash', table_name='user')
    op.drop_column('user', 'pw_hash')
    ### end Alembic commands ###
