"""empty message

Revision ID: acbe1fecdc3
Revises: None
Create Date: 2014-03-23 01:10:40.401464

"""

# revision identifiers, used by Alembic.
revision = 'acbe1fecdc3'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_email', 'user', ['email'], unique=True)
    op.create_index('ix_user_name', 'user', ['name'], unique=True)
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.func.current_timestamp(), nullable=True),
    sa.Column('unread', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_message_title', 'message', ['title'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_message_title', table_name='message')
    op.drop_table('message')
    op.drop_index('ix_user_name', table_name='user')
    op.drop_index('ix_user_email', table_name='user')
    op.drop_table('user')
    ### end Alembic commands ###
